name: Patch IPA

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'Direct link to IPA file'
        required: true
      release_type:
        description: 'Release type (draft or full)'
        required: true
        default: 'draft'
        type: choice
        options:
          - draft
          - release

jobs:
  patch-ipa:
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install coreutils  # Untuk `timeout` & utilitas lainnya
          git clone https://github.com/Al4ise/Azule ~/Azule
          sudo ln -sf ~/Azule/azule /usr/local/bin/azule

      - name: Verify Azule Installation
        run: azule -h || echo "Azule installed successfully!"

      - name: Install wget (if not installed)
        run: |
          if ! command -v wget &> /dev/null; then
            brew install wget
          else
            echo "wget already installed, skipping..."
          fi

      - name: Create bin directory
        run: mkdir -p src/bin

      - name: Compile insert_dylib
        run:  |
          xcrun clang -v -o src/bin/insert_dylib src/insert_dylib/main.c
          chmod +x src/bin/insert_dylib

      - name: Make injector.sh executable
        run: chmod +x injector.sh

      - name: Download IPA
        run: |
          mkdir -p packages
          wget -O packages/downloaded.ipa "${{ github.event.inputs.ipa_url }}"

      - name: Patch IPA
        run: ./injector.sh packages/downloaded.ipa

      - name: Upload patched IPA
        uses: actions/upload-artifact@v4
        with:
          name: patched-ipa
          path: packages/*.ipa  # Ambil file IPA yang sudah dipatch tanpa rename

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/*.ipa  # Ambil file IPA yang sudah dipatch tanpa rename
          draft: ${{ github.event.inputs.release_type == 'draft' }}
          tag_name: patched-ipa-${{ github.run_number }}